docker services:
  database:
    image: postgres:alpine
    container_name: postgres_container
    environment:
      POSTGRES_DB: booth_art_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: oeuvre_api:latest
    container_name: app_container
    depends_on:
      - database
    ports:
      - "8080:8080"
    environment:
      DB_HOST: database
      DB_NAME: oeuvre_db
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    env_file:
      - .env

volumes:
  postgres_data:
