services:
  database:
    image: postgres:alpine
    container_name: oeuvre_db
    environment:
      POSTGRES_DB: oeuvre-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    env_file:
      - .env

  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: oeuvre_api:latest
    container_name: oeuvre_api
    depends_on:
      - database
    ports:
      - 8080:8080
    environment:
      DB_HOST: database
      DB_NAME: oeuvre-db
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    env_file:
      - .env

  ngrok:
    image: ngrok/ngrok:alpine
    restart: unless-stopped
    depends_on:
      - api
    command: start api --config /etc/ngrok.yml
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
    ports:
      - 4040:4040

volumes:
  postgres_data: