services:
  database:
    image: postgres:alpine
    container_name: oeuvre_db
    environment:
      POSTGRES_DB: oeuvre-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    env_file:
      - .env
#    profiles: [ "database" ]

  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: oeuvre_api:latest
    container_name: oeuvre_api
    depends_on:
      - database
    ports:
      - 8080:8080
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: oeuvre-db
      JWT_SECRET_KEY: aW5pc2VidWFocmFoYXNpYWRpYW50YXJha2l0YQ==
      JWT_EXPIRATION: 28800000
      DEFAULT_USERNAME: admin
      DEFAULT_PASSWORD: admin
      IMAGEKIT_PUBLIC_KEY: public_9/kchZ681GN70Jr9RZcY9ndIeOs=
      IMAGEKIT_SECRET_KEY: private_3sC99N3LKckSt8Xfxzxlggx5QyA=
      IMAGEKIT_ENDPOINT: https://ik.imagekit.io/muffincrunchy
      MIDTRANS_ENDPOINT: https://app.sandbox.midtrans.com/snap/v1/transactions
      MIDTRANS_MERCHANT_KEY: U0ItTWlkLXNlcnZlci14ZkU5RGFDZzdGTnZlenktX1ZReE9pUGk6
#    env_file:
#      - .env
#    profiles: [ "api" ]

#  ngrok:
#    image: ngrok/ngrok:alpine
#    container_name: oeuvre_server
#    restart: unless-stopped
#    entrypoint: ["ngrok", "start", "api", "--config", "/etc/ngrok.yml"]
#    volumes:
#      - ./ngrok.yml:/etc/ngrok.yml
#    ports:
#      - 4040:4040
#    profiles: [ "server" ]

#  minio:
#    image: minio/minio:RELEASE.2024-07-31T05-46-26Z
#    container_name: oeuvre_bucket
#    entrypoint: [ "minio", "server", "--address", "minio:9000", "--console-address", "minio:9001", "/data" ]
#    environment:
#      - MINIO_ROOT_USER=bucket-minio
#      - MINIO_ROOT_PASSWORD=bucket-minio
#    volumes:
#      - minio:/var/lib/minio/data
#    ports:
#      - 9000:9000
#      - 9001:9001
#    profiles: [ "bucket" ]

volumes:
  postgres: